spring:
  datasource:
    url: jdbc:sqlserver://spinguser.database.windows.net:1433;database=springdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: dbo.root
    password: Singapore@2025
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


